### ISSUE TITLE
 new page in pdf

### ISSUE THREAD

**Issue by fernandobonfimandrade** [joshua-gould/canvas2pdf#18]
Is there any method to create a new page inside PDF ?
How to configure page size?

**Comment by joshua-gould** [comment]
You can get the underlying pdfkit document (https://pdfkit.org/) using ctx.doc

**Comment by ferares** [comment]
@fernandobonfimandrade 
I know it's been a long time since you've asked the question but maybe someone else might find this useful.

If you need to setup the page size you'll actually need to pass that config option when creating the canvas2pdf context:

- Custom size: `const ctx = new canvas2pdf.PdfContext(blobStream(), { size: [width, height] })`
- Predefined size: `const ctx = new canvas2pdf.PdfContext(blobStream(), { size: 'A4' })`

https://pdfkit.org/docs/paper_sizes.html
